sudo: false
dist: xenial
os: linux
language: python
python:
- '3.7'
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- 'pypy3.5-6.0'
- 'pypy2.7-6.0'
matrix:
  include:
  - os: osx
    language: generic
    osx_image: xcode8.1
    # See also: https://github.com/Homebrew/homebrew-core/issues/6949
install:
  |
  if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    pip install --upgrade pip setuptools tox-travis;
  elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    brew tap drolando/homebrew-deadsnakes;
    brew install python34 python35 python36 python3 pypy
    pip install --upgrade pip setuptools
    pip install --user tox;
  fi
script: tox
