language: python
sudo: false
python:
- pypy
- pypy3
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
install:
- pip install -e .
- pip install flake8 pytest testtools
script:
- py.test --durations=10
- flake8 geofrontcli
