language: python
sudo: false
python:
- pypy-5.3.1
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install -e .
- pip install flake8 pytest testtools
script:
- py.test --durations=10
- flake8 geofrontcli
