sudo: false
dist: xenial
os: linux
language: python
python:
- '3.7'
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- 'pypy3.5-6.0'
- 'pypy2.7-6.0'
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: generic
    python: null
install:
  |
  if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    pip install --upgrade pip setuptools tox-travis
  elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    brew tap drolando/homebrew-deadsnakes
    brew install python34 python35 python36 python3 pypy
    pip install --upgrade pip setuptools
    pip install tox
  fi
script: tox
