language: python
sudo: false
python:
- pypy-5.3.1
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install -e .
- pip install flake8 pytest testtools
script:
- py.test --durations=10
- >
  if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then
    flake8 geofrontcli;
  fi
